server:
  port: 7000

spring:
  application:
    name: service-provider
dubbo:
  application:
    name: service-provider
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    port: 20880
    name: dubbo
    accesslog: true
  monitor:
    protocol: registry




